name: Python Tests with UI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Python dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure
      id: install_allure
      shell: pwsh
      run: |
        $allureVersion = "2.35.1"
        $allureUrl = "https://github.com/allure-framework/allure2/releases/download/$allureVersion/allure-$allureVersion.zip"
        $allureZip = "allure-$allureVersion.zip"
        $allureDir = "allure-$allureVersion"
        # 下载并解压
        Invoke-WebRequest -Uri $allureUrl -OutFile $allureZip
        Expand-Archive -Path $allureZip -DestinationPath .
        # 获取绝对路径
        $allurePath = (Resolve-Path $allureDir).Path
        $allureBin = Join-Path $allurePath "bin"
        # 添加到PATH
        "::add-path::$allureBin" | Out-File -FilePath $env:GITHUB_PATH -Append
        # 输出路径供后续步骤使用
        "allure_bin=$allureBin" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        "allure_version=$allureVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Run tests with smart handling
      id: smart_tests
      shell: pwsh
      run: |
        $ErrorActionPreference = "Continue"
        # 运行测试
        pytest -v test_cases/ui_tests/test_master_data/test_unitmeasure.py::TestUnitmeasurePage::test_add_unit --alluredir=allure-results --clean-alluredir
        $exitCode = $LASTEXITCODE
        # 输出退出码和结果
        "exit_code=$exitCode" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        # 分析退出码
        switch ($exitCode) {
            0 { 
                "result=success" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                Write-Host "✅ 所有测试通过"
                $finalExitCode = 0
            }
            1 { 
                "result=assertion_failure" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                Write-Host "⚠️ 断言失败，但继续执行后续步骤"
                $finalExitCode = 0
            }
            default { 
                "result=other_error" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                Write-Host "❌ 其他错误，停止执行后续步骤"
                $finalExitCode = $exitCode
            }
        }
        exit $finalExitCode

    - name: Generate Allure report
      if: always() && (steps.smart_tests.outputs.result == 'success' || steps.smart_tests.outputs.result == 'assertion_failure')
      shell: pwsh
      run: |
        # 使用之前步骤输出的 allure_bin 路径
        $allureBin = "${{ steps.install_allure.outputs.allure_bin }}"
        $allureCmd = Join-Path $allureBin "allure.bat"  # Windows 使用 .bat
        # 生成报告
        & $allureCmd generate allure-results -o allure-report --clean

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          allure-report
        retention-days: 30
