name: Python Tests with UI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract EdgeDriver
      run: |
        Expand-Archive -Path drivers/edgedriver_win64.zip -DestinationPath C:\SeleniumWebDrivers\Edge\
        echo "C:\SeleniumWebDrivers\Edge" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Extract Allure
      run: |
        Expand-Archive -Path allure/allure-2.35.1.zip -DestinationPath C:\allure\
        echo "C:\allure\allure-2.35.1\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests-ui
      continue-on-error: true
      run: |
        # 运行测试并输出详细结果
        pytest -v test_cases/ui_tests/test_master_data/test_unitmeasure.py::TestUnitmeasurePage::test_add_unit --alluredir=allure-results --clean-alluredir

    - name: Generate Allure report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path:
          allure-report/
        retention-days: 30
