name: Python Tests with UI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-edge:latest
        options: --shm-size=2g
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
        tar -zxvf allure-2.13.8.tgz
        sudo mv allure-2.13.8 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Run tests with smart handling
      id: smart_tests
      run: |
        set +e  # 禁用错误退出，让脚本继续执行
        
        # 运行测试，遇到第一个失败就停止（方便调试）
        pytest -v -x test_cases/ui_tests/test_master_data/test_material_management.py::TestMaterialManagement::test_add_material --alluredir=allure-results
        EXIT_CODE=$?
        
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        
        # 分析退出码
        case $EXIT_CODE in
            0)   # 全部通过
                echo "result=success" >> $GITHUB_OUTPUT
                echo "✅ 所有测试通过"
                ;;
            1)   # 断言失败
                echo "result=assertion_failure" >> $GITHUB_OUTPUT
                echo "⚠️ 断言失败，但继续执行后续步骤"
                ;;
            *)   # 其他错误（2,3,4,5等）
                echo "result=other_error" >> $GITHUB_OUTPUT
                echo "❌ 其他错误，停止执行后续步骤"
                ;;
        esac
        
        # 只有其他错误时才真正失败
        if [ $EXIT_CODE -eq 1 ] || [ $EXIT_CODE -eq 0 ]; then
            exit 0  # 返回成功，让后续步骤执行
        else
            exit $EXIT_CODE  # 返回原错误码，停止后续步骤
        fi
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        BASE_URL: ${{ secrets.BASE_URL }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    - name: Generate Allure report
      if: always() && (steps.smart_tests.outputs.result == 'success' || steps.smart_tests.outputs.result == 'assertion_failure')
      run: |
        echo "测试结果: ${{ steps.smart_tests.outputs.result }}"
        echo "生成Allure报告中..."
        allure generate allure-results -o allure-report --clean
        
        # 检查报告是否生成成功
        if [ -f "allure-report/index.html" ]; then
            echo "✅ Allure报告生成成功"
        else
            echo "❌ Allure报告生成失败"
            ls -la allure-results/ || echo "无测试结果数据"
        fi

    - name: Upload artifacts
      if: always() && (steps.smart_tests.outputs.result == 'success' || steps.smart_tests.outputs.result == 'assertion_failure')
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          allure-report/
          allure-results/
        retention-days: 30

    - name: Show final status
      if: always()
      run: |
        echo "=== 测试执行完成 ==="
        echo "最终结果: ${{ steps.smart_tests.outputs.result }}"
        echo "退出码: ${{ steps.smart_tests.outputs.exit_code }}"