name: Python Tests with UI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-edge:latest
        options: --shm-size=2g
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run specific test only
      run: |
        pytest -v test_cases/ui_tests/test_master_data/test_material_management.py::test_add_material --alluredir=allure_results
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

    - name: Generate and upload Allure report
      run: |
        # 安装 Allure
        curl -o allure-2.13.8.tgz -sL https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
        tar -zxvf allure-2.13.8.tgz
        ./allure-2.13.8/bin/allure generate allure-results -o allure-report --clean

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          allure-report/
          allure-results/
        retention-days: 30